model:
  dim: 768
  depth: 18
  num_heads: 12
  dropout: 0.1

optimizer:
  learning_rate: 3.0e-4
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.95
  eps: 1.0e-8

training:
  total_steps: 100000
  warmup_steps: 5000
  min_lr: 1.0e-6
  gradient_accumulation_steps: 2
  max_grad_norm: 1.0
  policy_weight: 1.0
  value_weight: 0.5
  use_ema: true
  log_interval: 100
  checkpoint_interval: 5000
  keep_checkpoints: 10

data:
  pgn_directory: "data/pgn"
  batch_size: 256          # 🟢 Auto تنظیم می‌شه طبق VRAM H200
  max_games: null
  min_elo: 2000
  max_elo: null
  min_moves: 10
  max_moves: 300
  result_filter: ['1-0', '0-1', '1/2-1/2']
  time_control_filter: null

gpu:
  force_gpu_type: null               # 🟢 خودش H200 رو می‌شناسه، لازم نیست override بدی
  max_split_size_mb: null            # 🟢 خودش تنظیم می‌کنه
  garbage_collection_threshold: null # 🟢 خودش تنظیم می‌کنه
  enable_compile: true
  compile_mode: "max-autotune"

paths:
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  tensorboard_dir: "runs"

advanced:
  seed: 42
  num_workers: null     # 🟢 Auto از GPU config
  pin_memory: true
  non_blocking: true
  detect_anomaly: false
  enable_profiling: false
  profile_steps: []
